export const CLICKED_XEM_TONG_QUAN = "CLICKED_XEM_TONG_QUAN";
export const CLICKED_QUAN_LY_DON_HANG = "CLICKED_QUAN_LY_DON_HANG";
export const CLICKED_QUAN_LY_KHACH_HANG = "CLICKED_QUAN_LY_KHACH_HANG";
export const CLICKED_QUAN_LY_SAN_PHAM = "CLICKED_QUAN_LY_SAN_PHAM";

export const CLICKED_QUAN_LY_MEDIA = "CLICKED_QUAN_LY_MEDIA";
export const CLICKED_QUAN_LY_VOUCHER = "CLICKED_QUAN_LY_VOUCHER";
export const CLICKED_QUAN_LY_HOAT_DONG = "CLICKED_QUAN_LY_HOAT_DONG";

export const WAITING_SERVER = "WAITING_SERVER";
export const CREATE_NHAN_HANG_SUCCESS = "CREATE_NHAN_HANG_SUCCESS";
export const BRAND_WAS_EXIST = "BRAND_WAS_EXIST";
export const RESET_BRAND_EXIST = "RESET_BRAND_EXIST";

export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CATEGORY_WAS_EXIST = "CATEGORY_WAS_EXIST";
export const RESET_CATEGORY_EXIST = "RESET_CATEGORY_EXIST";
export const WAITING_SERVER_CATEGORY = "WAITING_SERVER_CATEGORY";

export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const COLLECTION_WAS_EXIST = "COLLECTION_WAS_EXIST";
export const RESET_COLLECTION_EXIST = "RESET_COLLECTION_EXIST";
export const WAITING_SERVER_COLLECTION = "WAITING_SERVER_COLLECTION";

export const CREATE_COLOR_SUCCESS = "CREATE_COLOR_SUCCESS";
export const COLOR_WAS_EXIST = "COLOR_WAS_EXIST";
export const RESET_COLOR_EXIST = "RESET_COLOR_EXIST";
export const WAITING_SERVER_COLOR = "WAITING_SERVER_COLOR";

export const CREATE_SIZE_SUCCESS = "CREATE_SIZE_SUCCESS";
export const SIZE_WAS_EXIST = "SIZE_WAS_EXIST";
export const RESET_SIZE_EXIST = "RESET_SIZE_EXIST";
export const WAITING_SERVER_SIZE = "WAITING_SERVER_SIZE";

export const GET_VARIANTS_SUCCESS = "GET_VARIANTS_SUCCESS";

export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const PRODUCT_WAS_EXIST = "PRODUCT_WAS_EXIST";
export const RESET_PRODUCT_EXIST = "RESET_PRODUCT_EXIST";
export const WAITING_SERVER_PRODUCT = "WAITING_SERVER_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const PRODUCT_PAGE_CHANGE = "PRODUCT_PAGE_CHANGE";

export const OPEN_VARIANTS_FORM = "OPEN_VARIANTS_FORM";
export const OPEN_PRODUCT_FORM = "OPEN_PRODUCT_FORM";
export const CLOSE_VARIANTS_FORM = "CLOSE_VARIANTS_FORM";
export const CLOSE_PRODUCT_FORM = "CLOSE_PRODUCT_FORM";
//-----------------//
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const OFF_PRODUCT_DETAIL_UPDATE = "OFF_PRODUCT_DETAIL_UPDATE"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const RESET_UPDATE_STATE = "RESET_UPDATE_STATE"


export const OPEN_CONFIRM_DELETE = "OPEN_CONFIRM_DELETE"
export const CLOSE_CONFIRM_DELETE = "CLOSE_CONFIRM_DELETE"
export const GET_PRODUCT_DETAIL_DELETE = "GET_PRODUCT_DETAIL_DELETE"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const RESET_DELETE_STATE = "RESET_DELETE_STATE"