
export const TAO_MOI_USER = "TAO_MOI_USER"
export const GET_USER_ERROR = "GET_USER_ERROR"
export const SEND_INFOR_GOOGLE = "SEND_INFOR_GOOGLE"
export const SEND_INFOR_GITHUB = "SEND_INFOR_GITHUB"
export const PENDING_USER = "PENDING_USER"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_ALL_USER = "GET_ALL_USER"
export const USER_WAS_EXIST = "USER_WAS_EXIST"
export const GET_USER_TOKEN = "GET_USER_TOKEN"
export const PENDING_LOGIN = "PENDING_LOGIN"
export const GET_USER_FROM_TOKEN = "GET_USER_FROM_TOKEN"
export const UPDATE_AVATAR_IS_OK = "UPDATE_AVATAR_IS_OK"




